#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
echo "Executing pre-commit hook from `realpath -- $0`"

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi


# Cargo format
cargo fmt --package toybox -- --emit files
cargo fmt --package ctoybox -- --emit files
cargo fmt --package human_play -- --emit files
cargo fmt --package breakout-web-play -- --emit files
