#!/usr/bin/env python3

import argparse
import atari_py
import os

from atari_py.ale_python_interface import ALEInterface

def main(args):
  all_games = atari_py.list_games()
  if args.game not in all_games:
    starts_with = [g for g in all_games if g.startswith(args.game[0])]
    print('%s not found; did you mean:\n%s' % (args.game, '\t'.join(starts_with)))
    exit(0)


  game_path = atari_py.get_game_path(args.game)

  ale = ALEInterface()
  ale.setInt(b'random_seed', 1234)
  ale.loadROM(str.encode(game_path))
  
  legal_actions = ale.getLegalActionSet()

  frame_num = 0
  while not ale.game_over() and frame_num < args.num_frames:
    a = legal_actions[frame_num % len(legal_actions)]
    ale.act(a)    
    filename = args.game+str(frame_num).zfill(4)+'.png'
    frame_num += 1
    ale.saveScreenPNG(str.encode(args.output + os.sep + filename))
  

if __name__ == '__main__':
  parser = argparse.ArgumentParser()
  parser.add_argument('game', help='The name of the Atari game to extract from ALE.')
  parser.add_argument('--output', help='The output directory where the images should go (default is the current directory).', default='.')
  parser.add_argument('--num_frames', help='The number of frames we want to collect (default is 10).', default=10)
  parser.add_argument('--seed', help='The random seed for the Atari env (default is 1234).', default=1234)
  
  args = parser.parse_args()
  main(args)